version: '3.1'

services:
  vk-scan-comments:
    image: vk-scan-comments:latest
    restart: always
    environment:
      BOT_TOKEN:
      BOT_NICKNAME:
      ADMIN_TELEGRAM_ID:
      TELEGRAM_CHANNEL_ID:
      VK_ADD_IDS: 1,2,3
      VK_SECRET_KEYS: 5fae52db5fae52,438d1a8c438d1a8c43,caf82c53caf82c
      VK_GROUPS_IDS: -22822305,-22822306
      SCANNING_CRON: 0 0/30 * * * ?
      VK_API_DELAY: 50
