version: '3.1'

services:
  vk-scan-comments:
    image: vk-scan-comments:latest
    restart: always
    environment:
      BOT_TOKEN: 00000000000:AFASDFSCVASAFAFAFAFAF
      BOT_NICKNAME: vk_scan_bot
      ADMIN_TELEGRAM_ID: 00000000
      TELEGRAM_CHANNEL_ID: -00000000000000
      DB_URL: jdbc:postgresql://localhost:5432/postgres
      DB_USER: vk_scan_ro
      DB_PASSWORD: password
      VK_APP_IDS: 1,2,3
      VK_SECRET_KEYS: 5fae52db5fae52,438d1a8c438d1a8c43,caf82c53caf82c
      SCANNING_CRON: 0 0/10 * * * ?
      VK_API_DELAY: 50
